
- name: install pyenv
  shell: >-
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash &&
    echo "export PATH=\$PATH:\$HOME/.pyenv/bin:\$HOME/.pyenv/shims" >> ${HOME}/.zshenv &&
    echo "eval \"\$(pyenv init -)\"" >> ${HOME}/.zshenv &&
    echo "eval \"\$(pyenv virtualenv-init -)\"" >> ${HOME}/.zshenv &&
    source ${HOME}/.zshenv
    executable=/bin/bash
