- name: install mongoDB
  pacman: name=mongodb state=latest
  become: yes
  when: "ansible_os_family == 'Archlinux'"

- name: yum install mongoDB
  yum: name=mongodb state=latest
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: enable mongoDB
  systemd: name=mongodb enabled=yes state=started
  become: yes
  when: "ansible_os_family == 'Archlinux'"

- name: enable mongoDB
  service: name=mongodb enabled=yes state=started
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: install python modules
  pip: name=pymongo state=latest
  become: yes

