- name: install tkinter
  pacman: name={{ item }} state=latest
  with_items: '{{ depends }}'
  become: yes
  when: "ansible_os_family != 'RedHat'"

- name: install dependencies for building python
  yum: name={{ item }} state=latest
  with_items: '{{ depends_redhat }}'
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: install python
  shell: >-
    source ${HOME}/.zshenv ;
    pyenv install {{python.version}} ;
    pyenv rehash ;
    pyenv global {{python.version}}
    executable=/bin/bash

