# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.define :curry do |node|
  node.vm.box = "terrywang/archlinux"
  node.vm.network :private_network, ip: "192.168.33.66"
  node.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"
  node.vm.network :forwarded_port, guest: 5000, host: 5555
end
config.vm.provision "ansible" do |ansible|
  ansible.limit = "all"
  ansible.inventory_path = "provisioning/hosts"
  ansible.playbook = "provisioning/sites.yml"
end
  config.ssh.forward_agent = true
end
